### ISSUE TITLE
Add .gitignore for Python files

### ISSUE THREAD

**Issue by payton** [seerocode/reading-schedule#5]
There are a lot of extra files that don't need to be version controlled as per https://github.com/github/gitignore/blob/master/Python.gitignore

I created a branch on my fork with this update (just appended the above gitignore to the current one), but it's about ~5000 line changes. It would skew the contribution graph, so I figured you may prefer to do it (if interested in this change) :)

Thanks for creating this - It's just the tool I need and am looking forward to trying it out.

**Comment by payton** [comment]
For reference, here is my branch https://github.com/payton/reading-schedule/tree/add-gitignore

I also removed the vscode directory

**Comment by seerocode** [comment]
Thank you for pointing this out! Feel free to open a PR against this issue and I'll merge it in. The vscode settings were for my env so they can definitely be cleared from the repo.
